[package]
name = "interview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.11"
hyperloglog = "1.0.2"
rand = "0.8.5"


[profile.release]
debug = 1 
strip = false
lto = "fat"
